=head1 NAME

URI::ShortUrlServices::Expand -

=head1 SYNOPSIS

  use URI::ShortUrlServices::Expand;

  my $expander = URI::ShortUrlServices::Expand->new;
  my $url = $expander->expand( 'http://bit.ly/n9wIfh' );

  print $url # https://github.com/twittoru/p5-URI-ShortUrlServices-Expand;

=head1 DESCRIPTION

URI::ShortUrlServices::Expand is a expander for shorted URL with a simple redirection.
This library use the Wedata Database "Shorturlservices" or same format JSON file.

=head1 AUTHOR

Tor Ozaki E<lt>tor.ozaki@gmail.comE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

